# Generated by Django 5.0.4 on 2024-07-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Win',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
    ]
