# Generated by Django 5.0.4 on 2024-07-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='create_at_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
