# Generated by Django 5.0.4 on 2024-07-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_customer_create_at_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='Date',
            field=models.DateField(null=True, unique=True),
        ),
    ]
