# Generated by Django 5.0.4 on 2024-07-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='mail',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
